### ISSUE TITLE
Hamburgur menu in RTL languages displayed outside screen

### ISSUE THREAD

**Issue by alr86** [cuadratico/Click_Switch#1]
![Screenshot_۲۰۲۴۰۸۲۸-۲۱۳۵۵۱_Click.png](https://github.com/user-attachments/assets/fe06bc59-051d-403e-bc71-41140de30808)

**Comment by cuadratico** [comment]
Thanks for the comment, I hadn't thought about that so I'll adjust the
layout direction to LTR and RTL, in the next update I'll implement a system
so you have a second chance in hard mode, thanks for everything.

--cuadratico

**Comment by cuadratico** [comment]
I have already been able to fix this problem, to solve it I have forced all my activities to be in LTR. Solution implemented in version 8.7.6

**Comment by alr86** [comment]
Bug fixed
Thank you for your support❤️
